### ISSUE TITLE
Setup database schema

### ISSUE THREAD

**Issue by niclastanskanen** [Robrowno/operation2307#12]
Users Table:

- [x] id (primary key): Unique identifier for each user.
- [x] authentication: Authentication details for the user (e.g., email and password).
- [x] created_at: Timestamp indicating when the user was created.
- [x] modified_on: Timestamp indicating when the user record was last modified.

Images Table:

- [x] id (primary key): Unique identifier for each image.
- [x] user_id (foreign key): References the user who uploaded the image.
- [x] upload_image: Stores the image file or URL.
- [x] title: Title or name of the image.
- [x] description: Description or caption for the image.
- [x] date: Date associated with the image.
- [x] created_at: Timestamp indicating when the image was uploaded.
- [x] modified_on: Timestamp indicating when the image record was last modified.
- [x] approved: Boolean value indicating whether the image is approved and visible.
- [x] likes: Number of likes for the image.

Geolocation Table:

- [x] id (primary key): Unique identifier for each geolocation entry.
- [x] user_id (foreign key): References the user who captured the geolocation.
- [x] latitude: Stores the latitude coordinate from the image's geolocation.
- [x] longitude: Stores the longitude coordinate from the image's geolocation.
- [x] created_at: Timestamp indicating when the geolocation was captured.
- [x] modified_on: Timestamp indicating when the geolocation record was last modified.

**Comment by CallumDennisIE** [comment]
I think having a `modified_on` value for each model would be useful, and then a boolean value for `approved` so that we can control which posts are visible

**Comment by CallumDennisIE** [comment]
Possibly a `likes` value for the photos, so we can have some CRUD usage
